# Use Node.js image
FROM node:20

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .

# Expose the specified port
EXPOSE $PORT

# Start the server
CMD [ "node", "server.js" ]
